AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
Style/Documentation:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Max: 300
Metrics/ModuleLength:
  Max: 500
Naming/MethodParameterName:
  MinNameLength: 2
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
