apiVersion: k8s.groundstate.io/v1alpha1
kind: CloudServiceAccount
metadata:
  name: demo01
spec:
  policyTemplateValues:
    account: 000000000000
    bucket: arn:aws:s3:::buckit
  rolePolicyTemplate: |-
    {
      "Version": "2012-10-17",
      "Id": "S3-Account-Permissions for <%= account %>",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:Get*",
            "s3:List*",
            "s3:Describe*"
          ],
          "Resource": "<%= bucket %>"
        }
      ]
    }
  rolePolicyAttachments:
    - "arn:aws:iam::aws:policy/AmazonDocDBReadOnlyAccess"
    - "arn:aws:iam::aws:policy/AlexaForBusinessReadOnlyAccess"
    - "arn:aws:iam::aws:policy/AmazonCloudDirectoryReadOnlyAccess"
    - "arn:aws:iam::aws:policy/AmazonConnectReadOnlyAccess"
