name: Build and Release

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Rational for running manuualy
        required: false
        default: just cuz
  push:
    branches:
      - main
    paths:
      - lib/cloudsap/version.rb

jobs:
  release:
    env:
      BUILD_NAME: cloudsap
      VERSION_FILE: lib/cloudsap/version.rb
      CHANGELOG: CHANGELOG.md
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          RELEASE_VERSION=$(grep VERSION ${VERSION_FILE} | tr -d "VERSION= \'")
          RELEASE_BODY_PATH=body.md
          echo RELEASE_VERSION=${RELEASE_VERSION}     >> $GITHUB_ENV
          echo RELEASE_BODY_PATH=${RELEASE_BODY_PATH} >> $GITHUB_ENV
          sed -ne "/## ${RELEASE_VERSION}.*/,/#/p" ${CHANGELOG} | sed -e '$d' > $RELEASE_BODY_PATH
      - name: Create Release
        id: release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body_path: ${{ env.RELEASE_BODY_PATH }}
          draft: false
          prerelease: false
